### ISSUE TITLE
Add data field support for GRPC

### ISSUE THREAD

**Issue by gurinderhans** [axiomzen/gorush#11]
ref https://github.com/axiomzen/legends-api/issues/145

**Comment by gurinderhans** [comment]
If nested value fields are required in the future, we can set `NotificationRequest.data` to type `map<string, Value>` and then use the appropriate **Get** methods on the `Value` object, ex. `GetStringValue` or `GetNumberValue` (https://github.com/golang/protobuf/blob/master/ptypes/struct/struct.pb.go#L158).

It does require a small switch statement, but it's not too bad!

**Comment by Kay-Zee** [comment]
Addressed for now. May open again if something more than `map[string]string` is needed
